In [1]:
# importing numpy and pandas
import numpy as np
import pandas as pd

In [2]:
# Question 1: Version of NumPy is '1.20.1'
np.__version__

'1.20.1'

Version of Numpy is '1.20.1'

In [3]:

df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [4]:
# Question 2 : Number of Records in the Dataset
len(df)

11914

11914 are Number of Records in the Dataset 

In [5]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
# Question 3 : Who are the most frequent car manufacturers (top-3) according to the dataset? 
df["Make"]
df["Make"].value_counts()
df["Make"].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

Chevrolet, Ford, Volkswagen are the most frequent car manufacturers (top-3) according to the dataset

In [7]:
# Question 4 : What's the number of unique Audi car models in the dataset  34
df["Model"].nunique() # The overall Number of Car Model
df["Make"].nunique()  # The overall Number of Car Make/Manufacturers
df[df["Make"] == "Audi"].nunique() # Checking the number of unique Make/Manufacturers of Audi cars
df[df["Make"] == "Audi"].nunique().Model # Checking the number of unique Make/Manufacturers of Audi car Models

34

34 models are unique in the Audi car

In [8]:
# Question 5: Number of columns with missing values
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

5 columns are with missing values

In [9]:
# Question 6: Does the median value change after filling missing values?
    # 1.Find the median value of "Engine Cylinders" column in the dataset. 6.0
median_EC_before = df["Engine Cylinders"].median()
median_EC_before

6.0

In [10]:
    # 2.Next, calculate the most frequent value of the same "Engine Cylinders". 4.0
mode_EC = df["Engine Cylinders"].mode()
mode_EC


0    4.0
dtype: float64

In [11]:

    # 3.Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value (mode)} from the previous step.
df["Engine Cylinders"].fillna(df["Engine Cylinders"].mode(),inplace=True)

    # 4.Now, calculate the median value of "Engine Cylinders" once again.
median_EC_after = df["Engine Cylinders"].median()
median_EC_after

6.0

In [12]:
print(median_EC_before)
print(median_EC_after)

6.0
6.0


No, the median value did not change after filling missing values

In [13]:
# Question 7
    # 1. Select all the "Lotus" cars from the dataset.
df_Lotus = df[df["Make"] == "Lotus"]
    # Select only columns "Engine HP", "Engine Cylinders".
X = df_Lotus[["Engine HP", "Engine Cylinders"]]
    # Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).
    # Get the underlying NumPy array. Let's call it X.
X = df_Lotus[["Engine HP", "Engine Cylinders"]].drop_duplicates()
X

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [14]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
XT = X.T
XT


3912   3913   3918   4216   4257   4259   4262   4292  \
Engine HP         189.0  218.0  217.0  350.0  400.0  276.0  345.0  257.0   
Engine Cylinders    4.0    4.0    4.0    8.0    6.0    6.0    6.0    4.0   

                   4293  
Engine HP         240.0  
Engine Cylinders    4.0

In [15]:
XTX = np.dot(XT,X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [16]:
# Invert XTX.
XTX_inv = np.linalg.inv(XTX)
XTX_inv


array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [17]:
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array ([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [18]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inv.dot(XT).dot(y)
# What's the value of the first element of w? w = 4.59494481
w

array([  4.59494481, -63.56432501])

The value of the first element in w is 4.59494481